config/routes.rb
Rails.application.routes.draw do
  resources :histories
  get 'sessions/new'

  resources :members
  resources :admins
  get 'welcome/index'
  resources :books
  get 'books_controller/Book'
  post '/search' => 'books#search'
  post '/borrow' => 'books#borrow'
  post '/checkout' => 'books#checkout'
  get '/checkout/:id' => 'books#checkout'
  get 'list_book_history' => 'books#list_history'
  get 'list_member_history' => 'members#list_history'
  post 'return_book' => 'members#return_book'
  get '/books/:id/subscribe' => 'books#subscribe'
  get '/books/:id/unsubscribe' => 'books#unsubscribe'
  get '/suggestions' => 'suggestions#index'
  post '/suggestions' => 'suggestions#create'
  get '/suggestions/new' => 'suggestions#new', as: 'new_suggestion'

  get '/suggestions/:id/approve' => 'suggestions#approve', as: 'approve_suggestion'
  get '/suggestions/:id' => 'suggestions#show', as: 'suggestion'
  patch '/suggestions/:id' => 'suggestions#update'
  put '/suggestions/:id' => 'suggestions#update'
  delete '/suggestions/:id' => 'suggestions#destroy'

  root 'welcome#index'
  get 'login_member' => 'sessions#new_member'
  post 'login_member' => 'sessions#create_member'
  delete 'logout' => 'sessions#destroy'
  get 'login_admin' => 'sessions#new_admin'
  post 'login_admin' => 'sessions#create_admin'

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Admins List', admins_path %>
<%= link_to 'Books List', books_path %>

app/views/admins/index.html.erb
<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>

        <td><%= link_to 'Show', admin %></td>
        <% if((!(admin.preadmin)) && !(admin.id == current_user.id))%>
        <td><%= link_to 'Delete', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<td><% if current_user.class.to_s == 'Admin' %></td>
<td><%= link_to 'Edit my profile', edit_admin_path(current_user) %></td>
      <td><% end %></td>
<%= link_to 'New Admin', new_admin_path %>
<%= link_to 'Members List', members_path%>
  <%= link_to 'Books List', books_path%>
  <%= link_to 'Suggestions List', suggestions_path%>
  <%= link_to "Log out", logout_path, method: "delete" %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<% if @admin.id == current_user.id && @admin.preadmin != true %>
  <%= link_to 'Edit', edit_admin_path(@admin) %> | 
<% end %>

<%= link_to 'Back', admins_path %>