config/routes.rb
Rails.application.routes.draw do
  resources :histories
  get 'sessions/new'

  resources :members
  resources :admins
  get 'welcome/index'
  resources :books
  get 'books_controller/Book'
  post '/search' => 'books#search'
  post '/borrow' => 'books#borrow'
  post '/checkout' => 'books#checkout'
  get '/checkout/:id' => 'books#checkout'
  get 'list_book_history' => 'books#list_history'
  get 'list_member_history' => 'members#list_history'
  post 'return_book' => 'members#return_book'
  get '/books/:id/subscribe' => 'books#subscribe'
  get '/books/:id/unsubscribe' => 'books#unsubscribe'
  get '/suggestions' => 'suggestions#index'
  post '/suggestions' => 'suggestions#create'
  get '/suggestions/new' => 'suggestions#new', as: 'new_suggestion'

  get '/suggestions/:id/approve' => 'suggestions#approve', as: 'approve_suggestion'
  get '/suggestions/:id' => 'suggestions#show', as: 'suggestion'
  patch '/suggestions/:id' => 'suggestions#update'
  put '/suggestions/:id' => 'suggestions#update'
  delete '/suggestions/:id' => 'suggestions#destroy'

  root 'welcome#index'
  get 'login_member' => 'sessions#new_member'
  post 'login_member' => 'sessions#create_member'
  delete 'logout' => 'sessions#destroy'
  get 'login_admin' => 'sessions#new_admin'
  post 'login_admin' => 'sessions#create_admin'

end

app/models/book.rb
class Book < ActiveRecord::Base
  after_initialize :default_status
  validates :ISBN, presence: true, uniqueness: { case_sensitive: false }
  validates :title, presence: true
  validates :description, presence: true
  validates :authors, presence: true
  validates :status, presence: true, inclusion: { in: %w(Checked\ Out Available), message: "%{value} isn't a valid status for the book" }
  validates :holder, presence: true
  private
    def default_status
      self.status ||= "Available"
      self.holder ||= "Nobody"
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_filter :authenticate_admin, only: [:create, :edit, :update, :destroy], except: [:subscribe, :unsubscribe]
    before_filter :authenticate_member, only: [:subscribe, :unsubscribe]
  def index
    @books = Book.where(active: true)
  end
  def show
    @book = Book.find(params[:id])
    if @book.status != "Available"
      @history = History.where(book_id: @book.id, status: "Checkedout").first
      holder_email = @history.member_email
      @holder = Member.find_by(:email => holder_email)
    end
  end
  def new
    @book = Book.new
  end
  def edit
    @page = "edit"
    @book = Book.find(params[:id])
  end
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render 'new'
    end
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end
  def destroy
    @book = Book.find(params[:id])
    if !History.where(book_id: @book.id, status: "Checkedout").first
      @book.active = false
      if @book.save
        redirect_to books_url
      else
        render 'index'
      end
    else
      flash[:notice] = "Unable to Delete Book. Its been Borrowed. Please Return book before deleting it!"
      redirect_to '/books'
    end
  end
  def search
    logger.info "Here lies #{params[:item]}"
    @entry = Book.where(ISBN: params[:item], active: true) + Book.where(title: params[:item], active: true) + Book.where(authors: params[:item], active: true) + Book.where(status: params[:item], active: true)
    @entry = @entry.uniq
  end
  def checkout
    if session[:is_admin?]
      @is_admin = true
    else
      @is_admin = false
    end
    
    @history = History.new
    if @is_admin
      if Member.where(email: params[:item], active: true).first
      @history.member_email = params[:item]
    end
    else
      @history.member_email = session[:user_id]
    end
    @book = Book.find(params[:book_id])
    
    if @history.member_email != nil
      @history.book_id = params[:book_id]
      @history.checkout_at = Time.now.to_datetime
      @history.status = "Checkedout"
      logger.info "history: #{@history}"
      if @history.save
        @book.update_attribute(:status, "Checked Out")
        redirect_to @book
      
      end
    else
      flash[:error] = "Member doesn't exist. Please enter a valid email ID!"
      render 'checkout'
    end
  end
  
  def borrow
    #flash[:success] = "You have successfully checked out the book!"
    # @history = History.create(book_id:params[:book_id], member_email:params[:member_email], status:"Checkedout")
    if session[:is_admin?]
      @is_admin = true
    else
      @is_admin = false
    end
    @book = Book.find(params[:book_id])
    
  end
  def list_history
    @book = Book.find(params[:book_id])
    @history_list = History.where(book_id: @book.id)
    render 'list_history'
  end
  def subscribe
    @book = Book.find(params[:id])
    @user = Member.find_by(email: session[:user_id])
    @subscription = Subscription.where(member_email: @user.email, book_id: @book.id).first
    if !@subscription.nil?
      if @subscription.active == false
        @subscription.update_attribute(:active,true)
        flash[:notice] = "Subscribed to Book #{@book.title}!"
        Notify.notify_subscription(@user,@book).deliver_now
        render 'show'
      else
        flash[:notice] = "Already Subscribed!"
        render 'show'
      end
    else
      @subscription = Subscription.new(:member_email => session[:user_id],:book_id => @book.id)
      if @subscription.save
        flash[:notice] = "Subscribed to Book #{@book.title}!"
        Notify.notify_subscription(@user,@book).deliver_now
        render 'show'
      else
        flash[:notice] = "Error Subscribing to Book #{@book.title}"
        render 'show'
      end
    end
  end
  def unsubscribe
    @book = Book.find(params[:id])
    @user = Member.find_by(email: session[:user_id])
    @subscription = Subscription.where(active: true, member_email: @user.email, book_id: @book.id).first
    logger.info "logg #{@subscription}"
    if @subscription.update_attribute(:active,false)
      flash[:notice] = "Unsubscribed from Book #{@book.title}!"
      Notify.notify_unsubscription(@user,@book).deliver_now
      render 'show'
    else
      flash[:notice] = "Error Unsubscribing from Book #{@book.title}"
      render 'show'
    end
  end
  private
    def book_params
      params.require(:book).permit(:ISBN,:title,:authors,:description,:status)
    end
end

app/helpers/books_helper.rb
module BooksHelper
  def subscribed?(book_id)
    subscription = Subscription.where(active: true, member_email: session[:user_id], book_id: book_id).first
    if !subscription.nil?
      true
    else
      false
    end
  end
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= f.label :ISBN %><br>
  <%= f.text_field :ISBN %>
</p>

<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.label :authors %>
  <%= f.text_area :authors %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/books/_form_checkout.html.erb
<%= form_tag checkout_path do %>
  <p>
  <% if @is_admin %>
    <%= label_tag(:item, "Member Email: ") %>
    <%= text_field_tag :item %>
  <% end %>
  <%= hidden_field_tag :book_id, @book.id %>
  <%= submit_tag "CheckOut" %>
  </p>
<% end %>

app/views/books/_form_search.html.erb
<%= form_tag('/search', method: :post) do %>
  <p>
  <%= label_tag(:item, "Search: ") %>
  <%= text_field_tag(:item)  %>
  <%= submit_tag("Search") %>
  </p>
<% end %>

app/views/books/borrow.html.erb
<%= render 'form_checkout' %>
<p>
  ISBN : 
  <%= @book.ISBN %>
</p>

<p>
  Title : 
  <%= @book.title %>
</p>

<p>
  Description :
  <%= @book.description %>
</p>

<p>
  Authors :
  <%= @book.authors %>
</p>
<%= link_to 'Back', books_path %>

app/views/books/checkout.html.erb
<%= render 'form_checkout' %>
<% if flash[:error] %>
    <div class="error" style="color:red"><%= flash[:error] %></div>
  <% end %>
<p>
  ISBN : 
  <%= @book.ISBN %>
</p>

<p>
  Title : 
  <%= @book.title %>
</p>

<p>
  Description :
  <%= @book.description %>
</p>

<p>
  Authors :
  <%= @book.authors %>
</p>
<%= link_to 'Back', books_path %>

app/views/books/edit.html.erb
<h1> Editing Book </h1>
<%= render 'form' %>
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1> Listing Books </h1>
<p>
<%= render 'form_search' %>
</p>
<% if @books.exists? %>
  <table>
    <tr>
      <th>#</th>
      <th>ISBN</th>
      <th>Title</th>
      <th>Status</th>
    </tr>
    <% id=0 %>
    <% @books.each do |book| %>
      <tr>
        <td><%= id+=1 %></td>
        <td><%= book.ISBN %></td>
        <td><%= book.title %></td>
        <td><%= book.status %></td>
        <td><%= link_to 'Show', book_path(book) %></td>
        <% if book.status == "Available" %>
          <td><%= link_to 'Borrow', borrow_path(:book_id => book.id), method: :post %></td>
        <% end %>
        <td><% if session[:is_admin?] %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><% end %></td>
      <tr>
    <% end %>
  </table>
<% else %>
  <h3>No Books in our Library :'(</h3>
<% end %>

<td><% if current_user.class.to_s == 'Member' %></td>
      <td><%= link_to 'View my profile', member_path(current_user) %></td>
      <td><%= link_to 'Edit my profile', edit_member_path(current_user) %></td>
      <td><%= link_to 'New Suggestion', new_suggestion_path(current_user) %></td>
      <td><% end %></td>
  <td><% if current_user.class.to_s == 'Admin' %></td>
    <td><%= link_to 'New book', new_book_url %></td>
    <td><%= link_to 'View my profile', admin_path(current_user) %></td>
    <td><%= link_to 'Edit my profile', edit_admin_path(current_user) %></td>
    <td><%= link_to 'Suggestions List', suggestions_path %></td>
    <td><%= link_to 'Members List', members_path %></td>
    <td><%= link_to 'Admins List', admins_path %></td>
        <% end %>
<%= link_to "Log out", logout_path, method: "delete" %>

app/views/books/list_history.html.erb
<p>
<h2><%= "Checkout History of \"" + @book.title + "\""%></h2>
</p>
<% if @history_list.any? %>
  <table>
    <tr>
      <th>#</th>
      <th>Member</th>
      <th>Checkout Time</th>
      <th>Return Time</th>
    </tr>
    <% id=0 %>
    <% @history_list.each do |hs| %>
      <tr>
        <td><%= id+=1 %></td>
        <td><% member = Member.where(email: hs.member_email, active: true).first %>
            <% if member %>
              <%= member.name %>
            <% else %>
            Anonymous
            <% end %>
        </td>
        <td><%= hs.checkout_at %></td>
        <% if hs.return_at == nil %>
          <td> <center>-</center> </td>
        <% else %>
          <td><%= hs.return_at %></td>
        <% end %>
      <tr>
    <% end %>
  </table>
<% else %>
  <h3>No Checkout History found.</h3>
<% end %>

<%= link_to 'Back', book_path(@book) %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render 'form' %>
<%= link_to 'Back', books_url %>

app/views/books/search.html.erb
<%= render 'form_search' %>
<% if !@entry.nil? %>
  <% id=0 %>
  <h4><%= @entry.count %> entries found</h4>
  <% @entry.each do |x| %>
    <p>
    <h4><%= id+=1 %>. <%= x.title %></h4>
    </p>
    <p>
    ISBN : <%= x.ISBN %>
    </p>
    <p>
    Description : <%= x.description %>
    </p>
    <p>
    Authors : <%= x.authors %>
    </p>
    <p>
    Status : <%= x.status %>
    </p>
    <%= link_to 'Show', "/books/#{x.id}" %>
  <% end %>
<% else %>
  <h3>No Books found. Please Try Again</h3>
<% end %>

<br><%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
<h2><%= @book.title %></h2>
</p>

<p>
  <strong> ISBN:</strong>
  <%= @book.ISBN %>
</p>
<p>
  <strong> Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong> Authors:</strong>
  <%= @book.authors %>
</p>
<p>
  <strong> Status:</strong>
  <%= @book.status %>
</p>

<% if @book.status != "Available" and session[:is_admin?] %>
  <p>
    <strong> Holder:</strong>
    <%= @holder.name %>
  </p>
<% end %>
<% if session[:user_id] and subscribed?(@book.id) != true and @book.status != "Available"%>
  <%= link_to "Subscribe", :controller => :books, :action => :subscribe %>
<% else %>
  <% if session[:user_id] and @book.status != "Available" and subscribed?(@book.id) == true %>
    <%= link_to "Unsubscribe", :controller => :books, :action => :unsubscribe %>
  <% end %>
<% end %>
<%= link_to 'Checkout History', list_book_history_path(@book, :book_id => @book.id) %>

<br>
<% if session[:is_admin?] %>
<%= link_to 'Edit', edit_book_path(@book) %>
<% end %>
<%= link_to 'Back', books_url %>