config/routes.rb
Rails.application.routes.draw do
  resources :histories
  get 'sessions/new'

  resources :members
  resources :admins
  get 'welcome/index'
  resources :books
  get 'books_controller/Book'
  post '/search' => 'books#search'
  post '/borrow' => 'books#borrow'
  post '/checkout' => 'books#checkout'
  get '/checkout/:id' => 'books#checkout'
  get 'list_book_history' => 'books#list_history'
  get 'list_member_history' => 'members#list_history'
  post 'return_book' => 'members#return_book'
  get '/books/:id/subscribe' => 'books#subscribe'
  get '/books/:id/unsubscribe' => 'books#unsubscribe'
  get '/suggestions' => 'suggestions#index'
  post '/suggestions' => 'suggestions#create'
  get '/suggestions/new' => 'suggestions#new', as: 'new_suggestion'

  get '/suggestions/:id/approve' => 'suggestions#approve', as: 'approve_suggestion'
  get '/suggestions/:id' => 'suggestions#show', as: 'suggestion'
  patch '/suggestions/:id' => 'suggestions#update'
  put '/suggestions/:id' => 'suggestions#update'
  delete '/suggestions/:id' => 'suggestions#destroy'

  root 'welcome#index'
  get 'login_member' => 'sessions#new_member'
  post 'login_member' => 'sessions#create_member'
  delete 'logout' => 'sessions#destroy'
  get 'login_admin' => 'sessions#new_admin'
  post 'login_admin' => 'sessions#create_admin'

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  validates :member_email, presence: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  validates_numericality_of :ISBN, presence: true, uniqueness: { case_sensitive: false }, :in => 1..9223372036854775807
  validates :title, presence: true
  validates :description, presence: true
  validates :authors, presence: true
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_filter :authenticate_admin, only: [:index, :approve, :update, :destroy]
  before_filter :authenticate_member, only: [:create]
  def index
    @suggestions = Suggestion.where(active: true)
  end
  def show
    @suggestion = Suggestion.where(active: true, id: params[:id]).first
    if @suggestion
      render 'show'
    else
      flash[:notice] = "Page not Found!"
      redirect_to '/books'
    end
  end
  def new
    @suggestion = Suggestion.new
    @suggestion.member_email = session[:user_id]
  end
  def create
    @suggestion = Suggestion.new(suggestion_params)
    @suggestion.member_email = session[:user_id]
    if @suggestion.save
      redirect_to @suggestion
    else
      render 'new'
    end
  end
  def approve
    @page = "approve"
    @suggestion = Suggestion.find(params[:id])
  end
  def update
    @suggestion = Suggestion.find(params[:id])
    if @suggestion.update(suggestion_params)
      @suggestion.update_attribute(:active,false)
      @book = Book.new
      @book.ISBN = @suggestion.ISBN
      @book.title = @suggestion.title
      @book.description = @suggestion.description
      @book.authors = @suggestion.authors
      if @book.save
        flash[:notice] = "Suggestion for #{@suggestion.title} has been approved"
        redirect_to '/suggestions'
      end
    else
      flash[:notice] = "Error in Approving Suggestion for #{@suggestion.title}"
      render 'approve'
    end
  end
  def destroy
    @suggestion = Suggestion.find(params[:id])
 #   @suggestion.update_attribute(:active,false)
    @suggestion.active = false
    if @suggestion.save
      redirect_to suggestions_url
    else
      render 'index'
    end
  end

  private
  def suggestion_params
    params.require(:suggestion).permit(:member_email,:ISBN,:title,:authors,:description)
  end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/suggestions/_form.html.erb
<%= form_for @suggestion do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:
      </h2>
      <ul>
        <% @suggestion.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= f.label :ISBN %><br>
  <%= f.text_field :ISBN %>
</p>

<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.label :authors %>
  <%= f.text_area :authors %>
</p>

<p>
  <%= f.submit ("Submit") %>
</p>
<% end %>

app/views/suggestions/approve.html.erb
<h1> Approve Book </h1>
<%= render 'form' %>
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<h1> Listing Suggestions </h1>
<% if @suggestions.exists? %>
  <table>
    <tr>
      <th>#</th>
      <th>ISBN</th>
      <th>Title</th>
      <th>Suggested By</th>
    </tr>
    <% id=0 %>
    <% @suggestions.each do |suggestion| %>
      <tr>
        <td><%= id+=1 %></td>
        <td><%= suggestion.ISBN %></td>
        <td><%= suggestion.title %></td>
        <td><%= suggestion.member_email %></td>
        <td><%= link_to 'Show', suggestion_path(suggestion) %></td>
        <td><%= link_to 'Approve', approve_suggestion_path(suggestion) %></td>
        <td><%= link_to 'Delete', suggestion_path(suggestion), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      <tr>
  </table>
<% else %>
  <h3>No suggestions in our Library :'(</h3>
<% end %>
<% if current_user.class.to_s == 'Member' %>
  <td><%= link_to 'View my profile', member_path(current_user) %></td>
  <td><%= link_to 'Edit my profile', edit_member_path(current_user) %></td>
  <td><%= link_to 'New Suggestion', new_suggestion_path(current_user) %></td>
<% end %>
<% if current_user.class.to_s == 'Admin' %>
  <td><%= link_to 'New book', new_book_url %></td>
  <td><%= link_to 'View my profile', admin_path(current_user) %></td>
  <td><%= link_to 'Edit my profile', edit_admin_path(current_user) %></td>
  <td><%= link_to 'Books List', books_path%></td>
  <td><%= link_to 'Members List', members_path %></td>
  <td><%= link_to 'Admins List', admins_path %></td>
<% end %>
<%= link_to "Log out", logout_path, method: "delete" %>

app/views/suggestions/new.html.erb
<h1>New Suggestion</h1>
<%= render 'form' %>
<%= link_to 'Back', books_url %>

app/views/suggestions/show.html.erb
<p>
<h2><%= @suggestion.title %></h2>
</p>

<p>
  <strong> ISBN:</strong>
  <%= @suggestion.ISBN %>
</p>
<p>
  <strong> Description:</strong>
  <%= @suggestion.description %>
</p>

<p>
  <strong> Authors:</strong>
  <%= @suggestion.authors %>
</p>
<p>
  <strong> Suggested By:</strong>
  <%= @suggestion.member_email %>
</p>

<% if current_user.class.to_s == 'Admin' %>
  <%= link_to 'Approve', approve_suggestion_path(@suggestion, :suggestion_id => @suggestion.id) %>
<% end %>
<br>
<% if current_user.class.to_s == 'Admin' %>
  <%= link_to 'Back', suggestions_url %>
<% else %>
  <%= link_to 'Back', books_url %>
<% end %>