config/routes.rb
Rails.application.routes.draw do
  resources :histories
  get 'sessions/new'

  resources :members
  resources :admins
  get 'welcome/index'
  resources :books
  get 'books_controller/Book'
  post '/search' => 'books#search'
  post '/borrow' => 'books#borrow'
  post '/checkout' => 'books#checkout'
  get '/checkout/:id' => 'books#checkout'
  get 'list_book_history' => 'books#list_history'
  get 'list_member_history' => 'members#list_history'
  post 'return_book' => 'members#return_book'
  get '/books/:id/subscribe' => 'books#subscribe'
  get '/books/:id/unsubscribe' => 'books#unsubscribe'
  get '/suggestions' => 'suggestions#index'
  post '/suggestions' => 'suggestions#create'
  get '/suggestions/new' => 'suggestions#new', as: 'new_suggestion'

  get '/suggestions/:id/approve' => 'suggestions#approve', as: 'approve_suggestion'
  get '/suggestions/:id' => 'suggestions#show', as: 'suggestion'
  patch '/suggestions/:id' => 'suggestions#update'
  put '/suggestions/:id' => 'suggestions#update'
  delete '/suggestions/:id' => 'suggestions#destroy'

  root 'welcome#index'
  get 'login_member' => 'sessions#new_member'
  post 'login_member' => 'sessions#create_member'
  delete 'logout' => 'sessions#destroy'
  get 'login_admin' => 'sessions#new_admin'
  post 'login_admin' => 'sessions#create_admin'

end

app/models/member.rb
class Member < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  validates :password_digest, presence: true
  has_secure_password
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  #before_action :set_member, only: [:show, :edit, :update]
  before_filter :authenticate_member, except: [:index, :destroy]
  #before_filter :authenticate_admin, only: [:index, :show, :create, :edit, :destroy]
  # GET /members
  # GET /members.json
  def index
    @members = Member.where(active: true)
  end

  # GET /members/1
  # GET /members/1.json
  def show
    curr_user = Member.find_by(email: session[:user_id])
    if (curr_user && curr_user.id.to_s == params[:id]) || session[:is_admin?]
      @member = Member.find(params[:id])
      checkout_list = History.where(member_email: @member.email, status: "Checkedout")
      @book_list = []
      book_id_list = checkout_list.map { |x| x[:book_id] }
      book_id_list.each do |id|
        @book_list << id
      end
   else
     flash[:notice] = "No Monkey Business!"
     redirect_to '/books'                                                     
   end
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
    curr_user = Member.find_by(email: session[:user_id])
    if (curr_user && curr_user.id.to_s == params[:id]) || session[:is_admin?]
      @member = Member.find(params[:id])
      render 'edit'
    else
      flash[:notice] = "No Monkey Business!"
      redirect_to '/books'
    end
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.where(email: params[:member][:email]).first
    if @member
    @member.active = true
    @member.update(member_params)
    else
    @member = Member.new(member_params)
    end
    respond_to do |format|
      if @member.save
        Notify.welcome_email(@member).deliver_now
        if current_user.nil?
          log_in @member
          is_admin?
          format.html { redirect_to @member, notice: 'Member was successfully created.' }
          format.json { render :show, status: :created, location: @member }
        else
          format.html { redirect_to @member, notice: 'Member was successfully created.' }
          format.json { render :show, status: :created, location: @member }
        end
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
        if @member.update(member_params)
          format.html { redirect_to @member, notice: 'Member was successfully updated.' }
          format.json { render :show, status: :ok, location: @member }
        else
          format.html { render :edit }
          format.json { render json: @member.errors, status: :unprocessable_entity }
        end
    end
  end
  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    if !History.where(member_email: @member.email, status: "Checkedout").first
      @member.active = false

      if @member.save
        redirect_to members_url
      else
        render 'index'
      end
    else
      flash[:notice] = "Unable to Delete Member.Please Return his/her borrowed book(s) before deleting Member!"
      redirect_to "/members/#{params[:id]}"
    end
  end

  def list_history
    @member = Member.find_by(:email => params[:member_email])
    @history_list = History.where(member_email: params[:member_email])
    render 'list_history'
  end
  
  def return_book
    @member = Member.find(params[:member_id])
    # Modify book holder, status
    book = Book.find(params[:book_id])
    book.update_attribute(:status, "Available")
    @subscriptions = Subscription.where(active: true, book_id: book.id)
    @subscriptions.each do |subscription|
      member = Member.find_by(email: subscription.member_email)
      Notify.notify_availability(member,book).deliver_now
    end
    # add history
    @history = History.where(book_id: book.id,member_email: @member.email,status:'Checkedout').first
    @history.return_at = Time.now.to_datetime
    @history.update_attribute(:return_at,@history.return_at)
    @history.update_attribute(:status, "Returned")
    redirect_to @member
  end
  def suggest
    @suggest_book = Suggestion.new
    render 'suggest'
  end
  def suggest_update
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', books_path %>

app/views/members/index.html.erb
<h1>Listing Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.email %></td>

        <td><%= link_to 'Show', member %></td>
        <td><% if current_user.class.to_s == 'Admin' %></td>
              <td><%= link_to 'Delete', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><% end%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<td><% if current_user.class.to_s == 'Member' %></td>
<td><%= link_to 'Edit my profile', edit_member_path(current_user) %></td>
<td><%= link_to 'New Suggestion', new_suggestion_path(current_user) %></td>
      <td><% end %></td>

  <td><% if current_user.class.to_s == 'Admin' %></td>
        <% Rails.application.config.direcory_page = true %>
        <%= link_to 'New Member', new_member_path %>
        <td><%= link_to 'Admin list', admins_path(current_user) %></td>
        <td><%= link_to 'Suggestions list', suggestions_path %></td>
          <%= link_to 'Books List', books_path%>

        <td><% end%></td>
    <%= link_to "Log out", logout_path, method: "delete" %>

app/views/members/list_history.html.erb
<p>
<h2><%= "Checkout History of \"" + @member.name + "\""%></h2>
</p>
<% if @history_list.any? %>
  <table>
    <tr>
      <th>#</th>
      <th>Book</th>
      <th>Checkout Time</th>
      <th>Return Time</th>
    </tr>
    <% id=0 %>
    <% @history_list.each do |hs| %>
      <tr>
        <td><%= id+=1 %></td>
        <td><%= Book.find(hs.book_id).title %></td>
        <td><%= hs.checkout_at %></td>
        <% if hs.return_at == nil %>
          <td> <center>-</center> </td>
        <% else %>
          <td><%= hs.return_at %></td>
        <% end %>
      <tr>
    <% end %>
  </table>
<% else %>
  <h3>No Checkout History found.</h3>
<% end %>

<%= link_to 'Back', member_path(@member) %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<% if !Rails.application.config.directory_page.nil? %>
<%= link_to 'Back', books_path %>
<% else %>
    <%= link_to 'Back', root_url %>
<% end %>

app/views/members/show.html.erb
  
<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

  <strong>Checked Out Books:</strong>
  <table>
    <tr>
      <th>#</th>
      <th>Book</th>
    </tr>
    <% id=0 %>
    <% @book_list.each do |bk_id| %>
      <tr>
        <td><%= id+=1 %></td>
        <td><%= Book.find(bk_id).title %></td>
        <td><%= link_to 'Return', return_book_path(@member, :member_id => @member.id, :book_id => bk_id), 
                                  method: :post %></td>
      </tr>
    <% end %>
  </table>


<%= link_to 'Checkout History', list_member_history_path(@member, :member_email => @member.email) %>
<% if session[:is_admin?] %>
<%= link_to 'Back', members_path %>
<% else %>
    <%= link_to 'Back', books_path %>
<% end %>